### ISSUE TITLE
07-exploregss.Rmd modeling exercise missing solution 

### ISSUE THREAD

**Issue by demar01** [rstudio-education/dsbox#13]
Faded example for modeling is missing the solution:

m <- lm(email ~ educ + wrkstat + snap_insta, data = ___)
tidy(m)

Solution is:
m <- lm(email ~ educ + wrkstat + snap_insta, data = gss)
tidy(m)

**Comment by mine-cetinkaya-rundel** [comment]
Thank you, added now!
