### ISSUE TITLE
Unable to install tutorial "demar01/penguinsbox"

### ISSUE THREAD

**Issue by krashr-ds** [rstudio-education/dsbox#21]
Hi,

Sorry to be troublesome, but I have been working to get my computer to install the tutorial for useR! conference.  I have Linux Mint 19.3 / Ubuntu 18.04 and was able to upgrade R to latest version, and install all package dependencies (remotes, devtools, learnr), but when I try to use remotes package to install "demar01/penguinsbox" or "rstudio/parsons" I keep getting the following error:

remotes::install_github("demar01/penguinsbox") Error: Failed to install 'unknown package' from GitHub:   Timeout was reached: [api.github.com] Resolving timed out after 10000 milliseconds
--
 
Please advise if possible!

Many thanks :) 

Kylie

**Comment by mine-cetinkaya-rundel** [comment]
Hello, should this go to https://github.com/demar01/penguinsbox?

**Comment by krashr-ds** [comment]
Sorry
