### ISSUE TITLE
problema en la instalación de penguinsbox

### ISSUE THREAD

**Issue by blacahin** [rstudio-education/dsbox#22]
Installing package into ‘C:/Users/carabali/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
* installing *source* package 'penguinsbox' ...
** using staged installation
** inst
** help
No man pages found in package  'penguinsbox' 
*** installing help indices
  converting help for package 'penguinsbox'
    finding HTML links ... done
*** copying figures
** building package indices
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for 'penguinsbox' in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 namespace 'ellipsis' 0.3.1 is already loaded, but >= 0.3.2 is required
Error: loading failed
Execution halted
ERROR: loading failed
* removing 'C:/Users/carabali/Documents/R/win-library/4.0/penguinsbox'

**Comment by mine-cetinkaya-rundel** [comment]
Hello, should this go to https://github.com/demar01/penguinsbox?
